const fields = [ 'SessionName',
                 'SessionNumber',
                 'PlayerID',
                 'GameID',
                 'DeviceName',
                 'DeviceModel',
                 'DeviceType',
                 'DeviceUniqueIdentifier',
                 'SessionDuration',
                 'TimeStamp',
                 'SessionCompleted',
                 'TransitionCount',
                 'transitions.0.TransitionNo',
                 'transitions.0.TransistionName',
                 'transitions.0.TransitionTime',
                 'transitions.0.TransitionComplete',
                 'transitions.0.ErrorCount',
                 'transitions.0.proximityErrorCount',
                 'transitions.0.preservativeErrorCount',
                 'transitions.0.numToLetterCount',
                 'transitions.0.letterToNumCount',

                 'transitions.1.TransitionNo',
                 'transitions.1.TransistionName',
                 'transitions.1.TransitionTime',
                 'transitions.1.TransitionComplete',
                 'transitions.1.ErrorCount',
                 'transitions.1.proximityErrorCount',
                 'transitions.1.preservativeErrorCount',
                 'transitions.1.numToLetterCount',
                 'transitions.1.letterToNumCount',

                 'transitions.2.TransitionNo',
                 'transitions.2.TransistionName',
                 'transitions.2.TransitionTime',
                 'transitions.2.TransitionComplete',
                 'transitions.2.ErrorCount',
                 'transitions.2.proximityErrorCount',
                 'transitions.2.preservativeErrorCount',
                 'transitions.2.numToLetterCount',
                 'transitions.2.letterToNumCount',

                 'transitions.3.TransitionNo',
                 'transitions.3.TransistionName',
                 'transitions.3.TransitionTime',
                 'transitions.3.TransitionComplete',
                 'transitions.3.ErrorCount',
                 'transitions.3.proximityErrorCount',
                 'transitions.3.preservativeErrorCount',
                 'transitions.3.numToLetterCount',
                 'transitions.3.letterToNumCount',

                 'transitions.4.TransitionNo',
                 'transitions.4.TransistionName',
                 'transitions.4.TransitionTime',
                 'transitions.4.TransitionComplete',
                 'transitions.4.ErrorCount',
                 'transitions.4.proximityErrorCount',
                 'transitions.4.preservativeErrorCount',
                 'transitions.4.numToLetterCount',
                 'transitions.4.letterToNumCount',

                 'transitions.5.TransitionNo',
                 'transitions.5.TransistionName',
                 'transitions.5.TransitionTime',
                 'transitions.5.TransitionComplete',
                 'transitions.5.ErrorCount',
                 'transitions.5.proximityErrorCount',
                 'transitions.5.preservativeErrorCount',
                 'transitions.5.numToLetterCount',
                 'transitions.5.letterToNumCount',

                 'transitions.6.TransitionNo',
                 'transitions.6.TransistionName',
                 'transitions.6.TransitionTime',
                 'transitions.6.TransitionComplete',
                 'transitions.6.ErrorCount',
                 'transitions.6.proximityErrorCount',
                 'transitions.6.preservativeErrorCount',
                 'transitions.6.numToLetterCount',
                 'transitions.6.letterToNumCount',

                 'transitions.7.TransitionNo',
                 'transitions.7.TransistionName',
                 'transitions.7.TransitionTime',
                 'transitions.7.TransitionComplete',
                 'transitions.7.ErrorCount',
                 'transitions.7.proximityErrorCount',
                 'transitions.7.preservativeErrorCount',
                 'transitions.7.numToLetterCount',
                 'transitions.7.letterToNumCount',

                 'transitions.8.TransitionNo',
                 'transitions.8.TransistionName',
                 'transitions.8.TransitionTime',
                 'transitions.8.TransitionComplete',
                 'transitions.8.ErrorCount',
                 'transitions.8.proximityErrorCount',
                 'transitions.8.preservativeErrorCount',
                 'transitions.8.numToLetterCount',
                 'transitions.8.letterToNumCount',

                 'transitions.9.TransitionNo',
                 'transitions.9.TransistionName',
                 'transitions.9.TransitionTime',
                 'transitions.9.TransitionComplete',
                 'transitions.9.ErrorCount',
                 'transitions.9.proximityErrorCount',
                 'transitions.9.preservativeErrorCount',
                 'transitions.9.numToLetterCount',
                 'transitions.9.letterToNumCount',

                 'transitions.10.TransitionNo',
                 'transitions.10.TransistionName',
                 'transitions.10.TransitionTime',
                 'transitions.10.TransitionComplete',
                 'transitions.10.ErrorCount',
                 'transitions.10.proximityErrorCount',
                 'transitions.10.preservativeErrorCount',
                 'transitions.10.numToLetterCount',
                 'transitions.10.letterToNumCount',

                 'transitions.11.TransitionNo',
                 'transitions.11.TransistionName',
                 'transitions.11.TransitionTime',
                 'transitions.11.TransitionComplete',
                 'transitions.11.ErrorCount',
                 'transitions.11.proximityErrorCount',
                 'transitions.11.preservativeErrorCount',
                 'transitions.11.numToLetterCount',
                 'transitions.11.letterToNumCount',

                 'transitions.12.TransitionNo',
                 'transitions.12.TransistionName',
                 'transitions.12.TransitionTime',
                 'transitions.12.TransitionComplete',
                 'transitions.12.ErrorCount',
                 'transitions.12.proximityErrorCount',
                 'transitions.12.preservativeErrorCount',
                 'transitions.12.numToLetterCount',
                 'transitions.12.letterToNumCount',

                 'transitions.13.TransitionNo',
                 'transitions.13.TransistionName',
                 'transitions.13.TransitionTime',
                 'transitions.13.TransitionComplete',
                 'transitions.13.ErrorCount',
                 'transitions.13.proximityErrorCount',
                 'transitions.13.preservativeErrorCount',
                 'transitions.13.numToLetterCount',
                 'transitions.13.letterToNumCount',

                 'transitions.14.TransitionNo',
                 'transitions.14.TransistionName',
                 'transitions.14.TransitionTime',
                 'transitions.14.TransitionComplete',
                 'transitions.14.ErrorCount',
                 'transitions.14.proximityErrorCount',
                 'transitions.14.preservativeErrorCount',
                 'transitions.14.numToLetterCount',
                 'transitions.14.letterToNumCount',

                 'transitions.15.TransitionNo',
                 'transitions.15.TransistionName',
                 'transitions.15.TransitionTime',
                 'transitions.15.TransitionComplete',
                 'transitions.15.ErrorCount',
                 'transitions.15.proximityErrorCount',
                 'transitions.15.preservativeErrorCount',
                 'transitions.15.numToLetterCount',
                 'transitions.15.letterToNumCount',

                 'transitions.16.TransitionNo',
                 'transitions.16.TransistionName',
                 'transitions.16.TransitionTime',
                 'transitions.16.TransitionComplete',
                 'transitions.16.ErrorCount',
                 'transitions.16.proximityErrorCount',
                 'transitions.16.preservativeErrorCount',
                 'transitions.16.numToLetterCount',
                 'transitions.16.letterToNumCount',

                 'transitions.17.TransitionNo',
                 'transitions.17.TransistionName',
                 'transitions.17.TransitionTime',
                 'transitions.17.TransitionComplete',
                 'transitions.17.ErrorCount',
                 'transitions.17.proximityErrorCount',
                 'transitions.17.preservativeErrorCount',
                 'transitions.17.numToLetterCount',
                 'transitions.17.letterToNumCount',

                 'transitions.18.TransitionNo',
                 'transitions.18.TransistionName',
                 'transitions.18.TransitionTime',
                 'transitions.18.TransitionComplete',
                 'transitions.18.ErrorCount',
                 'transitions.18.proximityErrorCount',
                 'transitions.18.preservativeErrorCount',
                 'transitions.18.numToLetterCount',
                 'transitions.18.letterToNumCount',

                 'transitions.19.TransitionNo',
                 'transitions.19.TransistionName',
                 'transitions.19.TransitionTime',
                 'transitions.19.TransitionComplete',
                 'transitions.19.ErrorCount',
                 'transitions.19.proximityErrorCount',
                 'transitions.19.preservativeErrorCount',
                 'transitions.19.numToLetterCount',
                 'transitions.19.letterToNumCount',

                 'transitions.20.TransitionNo',
                 'transitions.20.TransistionName',
                 'transitions.20.TransitionTime',
                 'transitions.20.TransitionComplete',
                 'transitions.20.ErrorCount',
                 'transitions.20.proximityErrorCount',
                 'transitions.20.preservativeErrorCount',
                 'transitions.20.numToLetterCount',
                 'transitions.20.letterToNumCount',

                 'transitions.21.TransitionNo',
                 'transitions.21.TransistionName',
                 'transitions.21.TransitionTime',
                 'transitions.21.TransitionComplete',
                 'transitions.21.ErrorCount',
                 'transitions.21.proximityErrorCount',
                 'transitions.21.preservativeErrorCount',
                 'transitions.21.numToLetterCount',
                 'transitions.21.letterToNumCount',

                 'transitions.22.TransitionNo',
                 'transitions.22.TransistionName',
                 'transitions.22.TransitionTime',
                 'transitions.22.TransitionComplete',
                 'transitions.22.ErrorCount',
                 'transitions.22.proximityErrorCount',
                 'transitions.22.preservativeErrorCount',
                 'transitions.22.numToLetterCount',
                 'transitions.22.letterToNumCount',

                 'transitions.23.TransitionNo',
                 'transitions.23.TransistionName',
                 'transitions.23.TransitionTime',
                 'transitions.23.TransitionComplete',
                 'transitions.23.ErrorCount',
                 'transitions.23.proximityErrorCount',
                 'transitions.23.preservativeErrorCount',
                 'transitions.23.numToLetterCount',
                 'transitions.23.letterToNumCount'


                ];


                var GetFields = function()
                {
                  return fields;
                }


module.exports = { GetFields };
